### ISSUE TITLE
Train data source

### ISSUE THREAD

**Issue by agusvgomez** [lennijusten/TickIDNet#1]
I can't find where is the data used for training, please can you provide it?

**Comment by lennijusten** [comment]
Hi @agusvgomez, 
The majority of our training images come from the GBIF database and can be downloaded at the following DOIs:

Amblyomma americanum:
GBIF.org (16 July 2020) GBIF Occurrence Download https://doi.org/10.15468/dl.4gbcs6.

Dermacentor variabilis:
GBIF.org (16 July 2020) GBIF Occurrence Download https://doi.org/10.15468/dl.tyybke.

Ixodes scapularis:
GBIF.org (16 July 2020) GBIF Occurrence Download https://doi.org/10.15468/dl.sq29u5.

Some of our other images were collected under IRB protocols that do now allow us to share those images publically. 

Images from our laboratory test set come from the website https://www.tickreport.com/stats
