### ISSUE TITLE
Final Model not downloadable

### ISSUE THREAD

**Issue by rogomichael** [lennijusten/TickIDNet#2]
Dear colleague,
 I find your work interesting and was interested in downloading the final images for testing the code. I however get an error to the link you provided. could you please share a new link? Thanks

**Comment by lennijusten** [comment]
Hi! Just to clarify - are you interested in the final model weights or the final images?

**Comment by rogomichael** [comment]
Hi,
I am interested in the final weights. I'd really appreciate if you could
provide me with the link.

**Comment by adammaus** [comment]
Hi Lenni! This is Adam from CHESS, we are doing some work with TickIDNet in The Tick App. I also noticed that the Google Drive Model link in the README.md is showing a 404. Would it be possible to get a copy of the model? Thank you for providing all of this documentation.

**Comment by lennijusten** [comment]
Hi @rogomichael and @adammaus. Sorry for the delayed response. 

After some digging, it seems that I also cannot access the model weights since they were in the Google Drive associated with my wisc.edu email. I'll try a few other things, like checking an older local drive, but for now I'm afraid I can't provide a copy of the model. My sincere apologies for this.

**Comment by adammaus** [comment]
Hi @lennijusten I was about to find a copy of the model from Oct 2020 on one of the CHESS servers. We can make this publicly available, right? Do you have any thoughts about where we can store it? It is 180mb. Unfortunately, CHESS won't be able to house this long-term, my appointment with them will end soon.

**Comment by lennijusten** [comment]
Hi @adammaus - great that you found a copy! Yes - we can make it public. If you can share it with me somehow (AWS, GDrive, Box - whatever works best) I'm happy to store it on my end. 

All the best for whatever comes next after CHESS!

**Comment by adammaus** [comment]
Thanks! I'm moving departments at UW-Madison but won't get to work on The Tick App which I'll miss.

Anyways, here is a public link in a folder that belongs to the MCEVBD group. I would hope they'd keep it around but it would probably be best to have a more permanent location, just in case.
https://uwmadison.box.com/s/2zak42q7eo4ir76m9500lg2dkmx1e1ft

**Comment by lennijusten** [comment]
Sounds good. I saved a [public copy](https://drive.google.com/file/d/124IfnT6rNLhmPr_3vH62jrK3OLL_fFrI/view?usp=sharing) in my personal Drive and will add it to the README.
